import './globals.css';
import { Inter } from 'next/font/google';
import * as React from 'react';

const inter = Inter({ subsets: ['latin'] });

const num = 1;

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(num);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
